In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1


## Introduction of tensors

#### creating tensors

In [2]:
#scalar
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
#get tensor back as python int
scaler.item()

7

In [5]:
#vectors
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
 vector.ndim

1

In [7]:
#Matrix

MATRIX = torch.tensor([[7,8],
                        [9,10 ] ])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX.ndim

2

In [9]:
# Tensor

TENSOR = torch.tensor([[[1,3,2,3],
                        [4,7,5,2],
                        [2,9,5,3]]])

TENSOR

tensor([[[1, 3, 2, 3],
         [4, 7, 5, 2],
         [2, 9, 5, 3]]])

In [10]:
TENSOR.ndim

3

In [11]:
TENSOR.shape

torch.Size([1, 3, 4])

In [12]:
#create a random tensor of aize (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3461, 0.4614, 0.2940, 0.0283],
        [0.3814, 0.4784, 0.2759, 0.8877],
        [0.5484, 0.2660, 0.3663, 0.9981]])

In [13]:
 #create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [14]:
random_image_size_tensor

tensor([[[0.5396, 0.7823, 0.7369,  ..., 0.5995, 0.1943, 0.7574],
         [0.8786, 0.1281, 0.3779,  ..., 0.8484, 0.5877, 0.0346],
         [0.4766, 0.6072, 0.3617,  ..., 0.4789, 0.7934, 0.1405],
         ...,
         [0.5384, 0.0551, 0.1419,  ..., 0.8493, 0.6894, 0.3314],
         [0.4736, 0.5912, 0.5022,  ..., 0.1973, 0.7397, 0.4655],
         [0.4751, 0.1936, 0.8859,  ..., 0.0545, 0.9686, 0.6875]],

        [[0.8004, 0.6004, 0.7386,  ..., 0.9631, 0.2980, 0.5411],
         [0.2039, 0.0833, 0.5805,  ..., 0.0756, 0.0132, 0.5884],
         [0.5453, 0.7101, 0.2802,  ..., 0.3739, 0.1921, 0.9677],
         ...,
         [0.7911, 0.2352, 0.3777,  ..., 0.5130, 0.9325, 0.3255],
         [0.5341, 0.7649, 0.9125,  ..., 0.2807, 0.9989, 0.0239],
         [0.2875, 0.4496, 0.7401,  ..., 0.0023, 0.0305, 0.4458]],

        [[0.1495, 0.3475, 0.0491,  ..., 0.8057, 0.5387, 0.7606],
         [0.8323, 0.9848, 0.7858,  ..., 0.7794, 0.1385, 0.1927],
         [0.1837, 0.0259, 0.6392,  ..., 0.3785, 0.9123, 0.

In [15]:
torch.rand(3,3)

tensor([[0.3212, 0.8909, 0.4357],
        [0.9379, 0.2218, 0.9319],
        [0.1468, 0.9699, 0.7393]])

#### Zeros and Ones Tensor


In [16]:
  # Create a tensor of all zeros
  zeros = torch.zeros(4,4)
  zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
#create a tensor foall one
ones = torch.ones(4,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
ones.dtype

torch.float32

### Creating a range of tensor and tensors-like

In [19]:
# use torch.arange()
one_to_thousand  = torch.arange(start=0, end = 1000, step=60)
one_to_thousand

tensor([  0,  60, 120, 180, 240, 300, 360, 420, 480, 540, 600, 660, 720, 780,
        840, 900, 960])

In [20]:
# use torch.arange()
one_to_ten = torch.arange(0,10,1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
#creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor **datatypes**

In [22]:
#  float 32 Tensor
float_32_tensor = torch.tensor([3.0,4.0,5.0],dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([3., 4., 5.])

In [23]:
float_32_tensor.dtype

torch.float32

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [25]:
float_16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [26]:
float_16_tensor * float_32_tensor

tensor([ 9., 16., 25.])

In [27]:
int_32_tensor = torch.tensor([1,3,2], dtype = torch.int32)

In [28]:
float_32_tensor

tensor([3., 4., 5.])

### Manipluation of Tensors
Tensor opertions include:
* Addition
* Subtractions
* Multipliaton
* Division
* Matrix Multiplicatoin



In [29]:
#Addition
tensor = torch.tensor([1,3,2])
tensor + 10

tensor([11, 13, 12])

In [30]:
# Multiply tesnor by 10
tensor * 10

tensor([10, 30, 20])

In [31]:
# Subtract 10
tensor - 10

tensor([-9, -7, -8])

### Matrix Multiplicatoin


Two main ways of perfoming multiplicatoin in neural networks and deep learning:
1. Element-Wise Multiplication
2. Matrix Multiplcation (Dot Product)

There are two main rules that performing matrix multiplication needs to satisfy:

1.  The **unner dimensions** must match
* `(3, 2)  @  (3, 2)` won't work
* `(2, 3)  @  (3, 2)` will work
* `(3, 2)  @  (2, 3)` will work


2. The resulting matrix has the of the **outer dimensions**:

* `(2, 3) @ (3, 2) -> (2, 2)`
* `(3, 2) @  (2, 3) -> (3, 3)`








In [32]:
# Element Wise Multipliaton
print(tensor, "*", tensor)
print(f"Equauls: {tensor * tensor}")

tensor([1, 3, 2]) * tensor([1, 3, 2])
Equauls: tensor([1, 9, 4])


In [33]:
# Matrix Multiplicaiotn
torch.matmul(tensor, tensor)

tensor(14)

### One of the most common errors in deep learning: shape errors

In [34]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[8,3],
                         [4,5],
                         [11,12]])

In [35]:
torch.matmul(tensor_A, tensor_B) #torch.mm is the same as torch.matmul (it's na alias for writing less code )

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape , tensor_B.shape

To Fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B, tensor_B.shape

In [ ]:
tensor_B.T , tensor_B.T.shape

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_b = {tensor_B.shape} ")
print(f"New Shapes: tensor_A  = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output: \n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput Shape: {output.shape}")



## Finding the min, max, mean, sum, etc (tensor aggregatoin)

In [ ]:
# Create a tensor
x= torch.arange(0, 100, 10)
x

In [ ]:
# Find the min
torch.min(x), x.min()


In [ ]:
# Find the max
torch.max(x) , x.max()

In [ ]:
#find the mean - note : the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

In [ ]:
# Find the sum
torch.sum(x) , x.sum()

## Finding the positional min and max

In [ ]:
x

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

In [ ]:
x[0]

In [ ]:
# Find the position in tensor that has the maximum value with argmin() -> returns index position of target tensor where the maximum value occurs
x.argmax()

In [ ]:
x[9]

In [ ]:
x

## Rehsaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory a s the original tensors
* Stacking - Combine Multiple tensors on top of each other (vstack) or sidy by side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
*  Permute  - Return a view of the input with dimensions permuted (swapped) in a certain way



In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1. , 10.)
x, x.shape

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped , x_reshaped.shape

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

In [ ]:
# Changing z changes x (because a view of a tensor sahres the same memory as the original input )
z[:, 0] = 5
z , x

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

In [ ]:
x_reshaped.shape

In [ ]:
x_reshaped.squeeze()

In [ ]:
x_reshaped.squeeze().size()

In [ ]:
# torch.squeee() - remove all single dimensions froma target tensor
print(f"Previous tensor: {x_reshaped}")
print(f'previous shape: {x_reshaped.shape} ')

#remove extra dimensions from x_reshaped
x_sequeezed = x_reshaped.squeeze()
print(f"\n New tensor: {x_sequeezed}")
print(f"\n New shape: {x_sequeezed.shape}")

In [ ]:
# torch.unsqueeze() - adds a single dimensino to a target tensor at specfic dim 
print(f"Previous target: {x_sequeezed}")
print(f"Previous Shape: {x_sequeezed.shape}")
      
# Add on extra dimension with unsqueeze
x_unsqueezed = x_sequeezed.unsqueeze(dim=0)
print(f"\nNew Tensor: {x_unsqueezed}")
print(f"New Shape: {x_unsqueezed.shape} ")

In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specfied order
x_original = torch.rand(size=(224, 224, 3)) #[height, width, colour_channels]

#permute the original tensor to arearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1)
print(f" Previous shape: {x_original.shape}")
print(f" New shape: {x_permuted.shape}")

In [ ]:
x_original[0, 0, 0] = 33443
x_original[0, 0, 0], x_permuted[0, 0, 0]

## Indexing (selecting data from tensors)

Indexing with pytorch is similar to indexing with Numpy.

In [ ]:
# Creating a tensor
x = torch.arange(1, 10).reshape(1 , 3 , 3)
x, x.shape

In [ ]:
# Let's index on our new tensor
x[0]

In [ ]:
# Let's index on middle bracked
x[0][0]

In [ ]:
#let index on the most inner bracket
x[0][0][0]

In [ ]:
x[0][2][2]

In [ ]:
# get all values of the 0th and 1st dimension but only index 1 of 2n dimensino
x[:,:,1]

In [ ]:
# Get all values of the zero dimension but only the 1 index value of 1st and 2nd dim 
x[:,1,1]

## Pytroch Tensors and numpy

Numpy is a popular scientific Python numerical computing library

And because of this, PyTorch has functionality to interact with it.

* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> numpy -> `torch.Tensor.numpy()`



In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array  = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

In [ ]:
array.dtype

In [ ]:
tensor.dtype

In [ ]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

In [ ]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

In [ ]:
numpy_tensor.dtype

## Reproducbillity (Trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operatinos -> update random number to try and make them better representations of the data -> again -> again -> again ->.`

To Reduce the randomness in neural networks and Pytorch come the concept of **random seed**.

Essentially what the random seed does is "flabour" the randomness

In [ ]:
import torch

# Create two Random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

In [ ]:
#  Let's ame some random but reproducible tensors

# set the random see
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)

random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

In [ ]:
# Setip Device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/modles on the GPU is because a GPU results in faster computation

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3], device='cpu')

# Tensor not on GPU
print(tensor, tensor.device)

In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

## 4. Moving tensor back to the CPU

In [ ]:
# IF tensor is on GPU, can't transform it to Numpy
# Note: My tensor is just gpu by name. it's not gpu tensor because i don'g have gpu. if you have gpu tensor you cannot convert it into numpy
tensor_on_gpu.numpy()

In [ ]:
# To Fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu